config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  devise_for :users
  resources :users, only: :show
  resources :tags, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/messages', to: 'messages#reply'
  resources :recipes do
    resources :favorites, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user
  has_many :steps
  has_many :materials
  has_many :favorites,dependent: :destroy
  has_many :users, through: :favorites
  has_many :likes,dependent: :destroy
  has_many :users, through: :likes
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :questions, dependent: :destroy
  validates :name, :image, :comment, :category, presence: true
  accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :reject_steps
  # proc { |attributes| attributes['content'].blank? }
  accepts_nested_attributes_for :materials, allow_destroy: true, reject_if: :reject_materials
  # proc { |attributes| attributes['name'].blank? }
  
  mount_uploader :image, ImageUploader

  def reject_steps(attributes)
    exists = attributes[:id].present?
    empty = attributes[:content].blank?
    attributes.merge!(_destroy: 1) if exists && empty
    !exists && empty
  end

  def reject_materials(attributes)
    exists = attributes[:id].present?
    empty = attributes[:name].blank?
    attributes.merge!(_destroy: 1) if exists && empty
    !exists && empty
  end

  # タグ一覧の配列をeachで回し、それぞれのタグとrecipeのidをTag_mapに登録する
  def register_tags(tag_list)
    tag_list.each do |tag|
      TagMap.create(recipe_id: self.id, tag_id: tag.id)
    end
  end


  def update_tags(tag_list)
    delete_tags = self.tags - tag_list
    new_tags = tag_list - self.tags
    delete_tags.each{|tag| TagMap.find_by(recipe_id: self.id, tag_id: tag.id).delete}
    new_tags.each{|tag| TagMap.create(recipe_id: self.id, tag_id: tag.id)}
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipes, only: [:show, :edit]
  before_action :set_materials_and_steps, only: [:show, :edit]
  def index
    # ランキング機能はまだなので、仮に数字を入れる
    @rankings = Recipe.includes(:user).order('updated_at DESC').limit(10)
    @new_pickup = Recipe.last
    @new_rankings = Recipe.includes(:user).order('updated_at DESC').limit(6)
    @recipes = Recipe.includes(:user).page(params[:page]).per(12)
  end

  def show
    @recipe  = Recipe.find(params[:id])
    @favorite = Favorite.find_by(user_id: current_user.id, recipe_id: params[:id]) if signed_in?
    @like = Like.find_by(user_id: current_user.id, recipe_id: params[:id]) if signed_in?
    @message = Message.new

  end

  def new
    @recipe = Recipe.new
    6.times {
      @recipe.steps.build}
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      # タグの一覧を取得し、新しいタグは新規で登録
      tag_list = Tag.set_tags(params[:tag])
      # 取得したタグ一覧をTag_mapテーブルに保存
      @recipe.register_tags(tag_list)
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      tag_list = Tag.set_tags(params[:tag])
      @recipe.update_tags(tag_list)
      redirect_to @recipe
    else
      render :edit
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :comment, :build_time, :cost, :size, :point, :image, :category_id, steps_attributes: [:content, :image, :id], materials_attributes: [:name, :category, :id]).merge(user_id: current_user.id)
  end

  def set_recipes
    @recipe = Recipe.find(params[:id])
  end

  def set_materials_and_steps
    # レシピに紐づいているmaterialsのうち、categoryが0と1で分類し、それぞれを配列で保存。
    @materials_mate = @recipe.materials.select {|mate| mate.category == 0}
    @materials_tool = @recipe.materials.select { |mate| mate.category == 1}
    # こちらもコントローラで定義しておく。
    @steps = @recipe.steps
  end
end

app/views/recipes/_favorite.html.haml
- if favorite.nil?
  =link_to recipe_favorites_path(recipe), method: :post, class: "notFavoritted", remote: true do
    =fa_icon 'star'
    %p お気に入り
- else
  =link_to recipe_favorite_path(recipe, favorite), method: :delete, class: "favoritted", remote: true do
    =fa_icon 'star'
    %p お気に入りを外す

app/views/recipes/_index_all_recipe.html.haml
%h1.mainTitle レシピ一覧
.midThumRecipes
  - @recipes.each do |recipe|
    .subThumRecipe.clearfix
      = link_to recipe_path(recipe) do
        =image_tag recipe.image.to_s, class: 'subThumRecipe__image'
        %p.subThumRecipe__title= recipe.name
        %p.subThumRecipe__user= "投稿者：#{recipe.user.nickname}"
  = paginate @recipes

app/views/recipes/_index_new_rank.html.haml
%h1.mainTitle 新着レシピ
.leftContent
  %h2.subTitle 
    = fa_icon 'thumbs-up'
    今日のピックアップ
  .mainThumRecipe
    = link_to recipe_path(@new_pickup) do
      =image_tag @new_pickup.image.to_s, class: "mainThumRecipe__image"
    = link_to recipe_path(@new_pickup) do
      %p.mainThumRecipe__title=@new_pickup.name
      %p.mainThumRecipe__explain=@new_pickup.comment
    = link_to "#" do
      %p.mainThumRecipe__user="投稿者：#{@new_pickup.user.nickname}"

.rightContent
  %h2.title.subTitle 
    = fa_icon 'trophy'
    新着の人気レシピ
  .subThumRecipes
    -@new_rankings.each do |recipe|
      .subThumRecipe
        = link_to recipe_path(recipe) do
          =image_tag recipe.image.to_s, class: "subThumRecipe__image"
          %p.subThumRecipe__title=recipe.name

app/views/recipes/_index_popular_rank.html.haml
.recipeRanking
  %h3.mainTitle 人気のレシピ
  %ul.bigThumRecipes
    - @rankings.each do |recipe|
      %li.bigThumRecipe
        = link_to recipe_path(recipe) do
          =image_tag recipe.image.to_s, class: "bigThumRecipe__image"
          %h4.bigThumRecipe__title=recipe.name
          %p.bigThumRecipe__user="投稿者：#{recipe.user.nickname}"

app/views/recipes/_like.html.haml
- if like.nil?
  =link_to recipe_likes_path(recipe), method: :post, class: "notLiked", remote: true do
    =fa_icon 'star'
    %p="いいね：#{like_count}"
- else
  =link_to recipe_like_path(recipe, like), method: :delete, class: "liked", remote: true do
    =fa_icon 'star'
    %p="いいねを外す：#{like_count}"

app/views/recipes/_show_post.html.haml
.recipeBoard
  %h4.title 
    =fa_icon 'question-circle'
    質問掲示板(7件)
    = form_for [@recipe,@message] , class: "postForm" do |f|
      =f.text_field :context, placeholder: "質問内容を記入してください", class: "postForm__context"
      =f.submit "SEND", class: "postForm__send"
      =f.text_field :status, style: "display:none", value: "new"

  %p.recipeBoardButton 掲示板を開く
  -@recipe.questions.order('updated_at DESC').each do |question|
    .posts
      -question.messages.each do |message|
        - if message.is_recipe_user == 1
          / 質問投稿者がレシピ投稿者と異なる（質問）の場合
          .question.clearfix
            =link_to user_path(message.user), class: 'prof question__prof' do
              =image_tag message.user.avatar.to_s, class: 'icon question__icon'
              %p.name= message.user.nickname
            .comment.question__comment
              %p= message.context
              %p.comment__time= "投稿:#{message.created_at}"
              / 最初のメッセージのみ削除ボタンが表示され、questionごと全てのmessageを削除する
              / 削除ができるのは質問の投稿者もしくはレシピの投稿者
              - if message.is_first == 0 && current_user == message.user || message.is_first == 0 && current_user == @recipe.user
                =link_to '削除', recipe_message_path(@recipe, message), method: :delete, class: 'deleteButton'
        - else
          / 質問投稿者とレシピ投稿者が同じ（回答）の場合
          .reply.clearfix
            =link_to user_path(message.user), class: 'prof reply__prof' do
              =image_tag message.user.avatar.to_s, class: 'icon reply__icon'
              %p.name= message.user.nickname
            .comment.reply__comment
              %p= message.context
              %p.comment__time= "投稿:#{message.created_at}"
              / recipeユーザーとmessageユーザーが同じであるmessageの表示なので、message.user == recipe.userは確定。
              / current_userがどちらか（＝どちらにも）当てはまることを確認
              - if message.is_first == 0 && current_user == message.user
                =link_to '削除', recipe_message_path(@recipe, message), method: :delete, class: 'deleteButton'
      =form_tag '/messages', method: :post, class: '' do
        %input{type: "submit",id: 'replyButton', class: 'replyButton', value: '返信する'}
        %input{type: 'text', name: 'context', class: 'reply__comment comment', placeholder: '返信コメントを入力してください'}
        %input{type: 'text', name: 'question_id', value: "#{question.id}", style: 'display:none;'}
        %input{type: 'text', name: 'recipe_id', value: "#{@recipe.id}", style: 'display:none;'}

app/views/recipes/_show_related_recipes.html.haml
%h4.relatedRecipe
  =fa_icon 'undo'
  関連するレシピ
.midThumRecipes
  .subThumRecipe.clearfix
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu7.jpg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu1.jpg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu2.jpg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu3.jpeg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu4.jpeg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu5.jpg'}
      %p.subThumRecipe__title すげぇカツ丼

app/views/recipes/edit.html.haml
= form_for @recipe do |f|
  / form_forで@recipeの状態によって遷移先を変更。stepとmaterialはnested_attributesの形で入力し、コントローラの処理でこれらも同時に登録する
  .recipe.clearfix
    %h3.recipeTitle
      =f.text_field :name, placeholder: 'タイトルを入力　　例：ヒノキの机'
    / トップ部分、タイトル、画像、レシピの詳細
    .recipeCategory.clearfix
      %p カテゴリを選択
      / カテゴリを大カテゴリ→小カテゴリで表示
      =f.grouped_collection_select(:category_id, LargeCategory.all, :categories, :name, :id, :name)
    .recipeTop.clearfix
      .recipePhoto
        =f.label :image do
          =image_tag "#{@recipe.image}"
          %p 画像クリックで写真を選択

        =f.file_field :image, style: "display:none;"
      .recipeDetail
        %h6
          制 作 費 用：
          =f.text_field :cost,placeholder: '例：2,000円'
        %h6
          制 作 時 間：
          =f.text_field :build_time, placeholder: '例：４時間'
        %h6
          完成サイズ：
          =f.text_field :size, placeholder: '例：h200 x w200 x d200x'
        %h6.comment ひとこと
        =f.text_area :comment, class: "commentForm", placeholder: 'どのような目的で作ったか、使ってみてどうかなど、自由に入力してください。'
        / この部分は未完
        .tags
          %h6.comment タグ一覧
          -@recipe.tags.each_with_index do |tag, i|
            %input{type: "text", name:"tag[#{i}]", placeholder: '挿入したいタグを入力', value: tag.name}
          -((@recipe.tags.length)..5).each do |i|
            %input{type: "text", name:"tag[#{i}]", placeholder: '挿入したいタグを入力'}
      / 材料入力部分
    .recipeMates
      .recipeMate.recipeInfoBox.margin
        %h6.recipeInfoBox__title 使用した材料
        %ul.recipeInfoBox__contents
          / material_mate(@step.materialsのうちcategoryが0の配列)のうち、材料をeachで表示。indexをnested_attributeの番号に入れる。
          -@materials_mate.each.with_index do |mate, i|
            %li.affiTitle
              / nested_attributesで保存されるようにname, id等を変更
              %input{type: "text", name: "recipe[materials_attributes][#{i}][name]", id: "recipe_materials_attributes_#{i}_name", value: "#{mate.name}", placeholder: "例：天板 高さ100x横幅250x厚さ50 １枚"}
              %input{type: "text", value: "0", name:"recipe[materials_attributes][#{i}][category]", id: "recipe_materials_attributes_#{i}_category", style:"display:none;"}
              %input{type: "hidden",name: "recipe[materials_attributes][#{i}][id]", value: "#{mate.id}", id:"recipe_materials_attributes_#{i}_id"}
          / 値が登録されていない部分（最大６個）は空欄を入れるため、@materiasl_mateの個数から5までの範囲オブジェクトで繰り返し
          -((@materials_mate.length)..5).each do |i|
            %li.affiTitle
              %input{type: "text", name: "recipe[materials_attributes][#{i}][name]", id: "recipe_materials_attributes_#{i}_name", placeholder: "例：天板 高さ100x横幅250x厚さ50 １枚"}
              / valueは0＝材料で固定し、display:noneで表示させない
              %input{type: "text", value: "0", name:"recipe[materials_attributes][#{i}][category]", id: "recipe_materials_attributes_#{i}_category", style:"display:none;"}
      .recipeMate.recipeInfoBox
        %h6.recipeInfoBox__title 使用した工具
        %ul.recipeInfoBox__contents
          / @material_mateと構造は一緒
          -@materials_tool.each.with_index(7) do |mate, i|
            %li.affiTitle
              %input{type: "text", name: "recipe[materials_attributes][#{i}][name]", id: "recipe_materials_attributes_#{i}_name", value: "#{mate.name}", placeholder: "例：電動ノコギリ"}
              %input{type: "text", value: "1", name:"recipe[materials_attributes][#{i}][category]", id: "recipe_materials_attributes_#{i}_category", style:"display:none;"}
              %input{type: "hidden", name: "recipe[materials_attributes][#{i}][id]", value: "#{mate.id}", id:"recipe_materials_attributes_#{i}_id"}
          / 値が登録されていない部分（最大６個）は空欄を入れるため、@materiasl_mateの個数から5までの範囲オブジェクトで繰り返し
          -((@materials_tool.length+11)..16).each do |i|
            %li.affiTitle
              %input{type: "text", name: "recipe[materials_attributes][#{i}][name]", id: "recipe_materials_attributes_#{i}_name", placeholder: "例：電動ノコギリ"}
              / valueは1=工具で固定し、display:noneで表示させない
              %input{type: "text", value: "1", name:"recipe[materials_attributes][#{i}][category]", id: "recipe_materials_attributes_#{i}_category", style:"display:none;"}
  / レシピ作成手順入力画面
  .recipeSteps.clearfix
    / @materials_mateと構造は一緒。すでに@recipeに登録されている@stepsを表示し、値が登録されていない部分（最大６個）は空欄を入れる。
    -@steps.each.with_index(1) do |step, i|
      .recipeStep
        .recipeStep__stepNum 
          STEP .
          %span=i
        .recipeStep__stepDetail.claerfix
          %label{for: "recipe_steps_attributes_#{i}_image"}
            %image.recipeStep__stepDetail__pic{src: "#{step.image}"}
            .imageButton.clearfix
              =fa_icon 'facebook'
              %p 画像を登録する
            %input{type: "file", name: "recipe[steps_attributes][#{i}][image]", id: "recipe_steps_attributes_#{i}_image", style: "display:none;", class: "clearfix"}
          %textarea{tyep: "text", name: "recipe[steps_attributes][#{i}][content]", id: "recipe_steps_attributes_#{i}_content", value: "#{step.content}", class: "recipeStep__stepDetail__comment",placeholder: "行程を入力してください"}
          %input{type: "hidden", name: "recipe[steps_attributes][#{i}][id]", value: "#{step.id}", id:"recipe_steps_attributes_#{i}_id"}
    - ((@steps.length+1)..6).each do |i|
      .recipeStep
        .recipeStep__stepNum 
          STEP .
          %span=i
        .recipeStep__stepDetail.claerfix
          %label{for: "recipe_steps_attributes_#{i}_image"}
            %image.recipeStep__stepDetail__pic{src: '/assets/katsu1.jpg', style: 'display:none;'}
            .imageButton.clearfix
              =fa_icon 'facebook'
              %p 画像を登録する
            %input{type: "file", name: "recipe[steps_attributes][#{i}][image]", id: "recipe_steps_attributes_#{i}_image", style: "display:none;"}
          %textarea{tyep: "text", name: "recipe[steps_attributes][#{i}][content]", id: "recipe_steps_attributes_#{i}_content", class: "recipeStep__stepDetail__comment", placeholder: "行程を入力してください"}
    .recipePoint.recipeInfoBox.margin
      %h6.recipeInfoBox__title コツ・ポイント
      %p.recipeInfoBox__content=f.text_area :point
  =f.submit "レシピを更新する", class: "amazonButton submitRecipe"

app/views/recipes/index.html.haml
= content_for :recipe_rank do
  =render 'index_popular_rank'
.content.clearfix
  =render 'index_new_rank'
.content.clearfix
  =render 'index_all_recipe'

app/views/recipes/new.html.haml
= form_for @recipe do |f|
  / form_forで@recipeの状態によって遷移先を変更。stepとmaterialはnested_attributesの形で入力し、コントローラの処理でこれらも同時に登録する
  .recipe.clearfix
    %h3.recipeTitle
      =f.text_field :name, placeholder: 'タイトルを入力　　例：ヒノキの机'
    / トップ部分、タイトル、画像、レシピの詳細
    .recipeCategory.clearfix
      %p カテゴリを選択
      / カテゴリを大カテゴリ→小カテゴリで表示
      =f.grouped_collection_select(:category_id, LargeCategory.all, :categories, :name, :id, :name)
    .recipeTop.clearfix
      / 画像をクリックでファイル選択が開くよう、画像をlabel化、ファイル選択画面はdisplay:noneで表示しない
      .recipePhoto
        =f.label :image do
          =image_tag '/assets/katsu1.jpg'
          %p 画像クリックで写真を選択

        =f.file_field :image, style: "display:none;"
      .recipeDetail
        %h6
          制 作 費 用：
          =f.text_field :cost,placeholder: '例：2,000円'
        %h6
          制 作 時 間：
          =f.text_field :build_time, placeholder: '例：４時間'
        %h6
          完成サイズ：
          =f.text_field :size, placeholder: '例：h200 x w200 x d200x'
        %h6.comment ひとこと
        =f.text_area :comment, class: "commentForm", placeholder: 'どのような目的で作ったか、使ってみてどうかなど、自由に入力してください。'
        / この部分は未完
        .tags
          %h6.comment タグ一覧を入力
          - 6.times do |i|
            %input{type: "text", name:"tag[#{i}]", placeholder: '挿入したいタグを入力'}
      / 材料入力部分
    .recipeMates
      .recipeMate.recipeInfoBox.margin
        %h6.recipeInfoBox__title 使用した材料
        %ul.recipeInfoBox__contents
          / 以下はnested_attributesの番号、6つ作成する
          -(0..5).each do |i|
            %li.affiTitle
              / name、idをiに合わせて変更
              %input{type: "text", name: "recipe[materials_attributes][#{i}][name]", id: "recipe_materials_attributes_#{i}_name", placeholder: "例：天板 高さ100x横幅250x厚さ50 １枚"}
              / valueは0＝材料で固定し、display:noneで表示させない
              %input{type: "text", value: "0", name:"recipe[materials_attributes][#{i}][category]", id: "recipe_materials_attributes_#{i}_category", style:"display:none;"}
      .recipeMate.recipeInfoBox
        %h6.recipeInfoBox__title 使用した工具
        %ul.recipeInfoBox__contents
          / 上と同じだが、JSで入力欄を増やす可能性があるため、数字は10~にしておく
          -(10..15).each do |i|
            %li.affiTitle
              %input{type: "text", name: "recipe[materials_attributes][#{i}][name]", id: "recipe_materials_attributes_#{i}_name", placeholder: "例：電動ノコギリ"}
              / valueは1=工具で固定し、display:noneで表示させない
              %input{type: "text", value: "1", name:"recipe[materials_attributes][#{i}][category]", id: "recipe_materials_attributes_#{i}_category", style:"display:none;"}
  / レシピ作成手順入力画面
  .recipeSteps.clearfix
    / @materials_mateと構造は一緒。すでに@recipeに登録されている@stepsを表示し、値が登録されていない部分（最大６個）は空欄を入れる。
    - (1..6).each do |i|
      .recipeStep
        .recipeStep__stepNum 
          STEP .
          %span=i
        .recipeStep__stepDetail.claerfix
          %label{for: "recipe_steps_attributes_#{i}_image"}
            %image.recipeStep__stepDetail__pic{src: '/assets/katsu1.jpg', style: 'display:none;'}
            .imageButton.clearfix
              =fa_icon 'facebook'
              %p 画像を登録する
            %input{type: "file", name: "recipe[steps_attributes][#{i}][image]", id: "recipe_steps_attributes_#{i}_image", style: "display:none;"}
          %textarea{type: "text", name: "recipe[steps_attributes][#{i}][content]", id: "recipe_steps_attributes_#{i}_content", class: "recipeStep__stepDetail__comment", placeholder: "行程を入力してください"}
    .recipePoint.recipeInfoBox.margin
      %h6.recipeInfoBox__title コツ・ポイント
      %p.recipeInfoBox__content=f.text_area :point, placeholder: "作成する上で、コツやポイントがあれば入力してください。"
  =f.submit "レシピを登録する", class: "amazonButton submitRecipe"

app/views/recipes/show.html.haml
- add_breadcrumb @recipe.category.large_category.name , "#"
- add_breadcrumb @recipe.category.name, '#'
- add_breadcrumb @recipe.name, '#'

.clearfix
  .recipe
    =render "shared/breadcrumbs"
    %h3.recipeTitle=@recipe.name
    .recipeAuthor.clearfix
      =link_to "投稿者：そばめし", '#', class: "authorLink"
      =link_to "削除する", '#', class: "editLink"
      =link_to "編集する", edit_recipe_path(@recipe), class: "editLink"
    .recipeFavo.clearfix{style: "#{'pointer-events:none;' unless signed_in?}"}
      .recipeFavo__like
        = render partial: "like", locals: {recipe: @recipe, like: @like}
      .recipeFavo__favorite
        = render partial: "favorite", locals: {recipe: @recipe, favorite: @favorite}
      .recipeFavo__facebook
        = link_to '#', class: "recipeFavo__facebook" do
          =fa_icon 'facebook-square'
          %p シェアする
      .recipeFavo__twitter
        = link_to '#', class: "recipeFavo__twitter noMarginRight" do
          =fa_icon 'twitter-square'
          %p ツイートする
    .recipeTop.clearfix
      .recipePhoto
        =image_tag  "#{@recipe.image}"
      .recipeDetail
        %h6
          制 作 費 用：
          %span=@recipe.cost
        %h6
          制 作 時 間：
          %span=@recipe.build_time
        %h6
          完成サイズ：
          %span=@recipe.size
        %h6.comment ひとこと
        %p=@recipe.comment
        .tags
          %h6.comment タグ一覧
          - @recipe.tags.each do |tag|
            = link_to tag_path(tag) do
              =fa_icon 'tag'
              =tag.name
    .recipeMates
      .recipeMate.recipeInfoBox.margin
        %h6.recipeInfoBox__title 使用した材料
        %ul.recipeInfoBox__contents
          -if @materials_mate.present?
            - @materials_mate.each do |mate|
              %li.affiTitle
                %p=mate.name
                %a.affiLink.clearfix{href:'#'}
                  %image.affiLink__img{src:'/assets/katsu1.jpg'}
                  %p.affiLink__name いい感じの豚骨やああああああああああああああああああ
                  %p.affiLink__price ¥2,000
      .recipeMate.recipeInfoBox
        %h6.recipeInfoBox__title 使用した工具
        %ul.recipeInfoBox__contents
          -if @materials_tool.present?
            - @materials_tool.each do |tool|
              %li.affiTitle
                %p=tool.name
                %a.affiLink.clearfix{href:'#'}
                  %image.affiLink__img{src:'/assets/katsu1.jpg'}
                  %p.affiLink__name いい感じの豚骨やああああああああああああああああああ
                  %p.affiLink__price ¥2,000
    %a.amazonButton
      =fa_icon 'amazon'
      Amazonで購入する
    .recipeSteps.clearfix
      -if @steps.present?
        -@steps.each.with_index(1) do |step, i|
          .recipeStep
            .recipeStep__stepNum 
              STEP .
              %span=i
            .recipeStep__stepDetail.claerfix
              -unless step.image.blank?
                %image.recipeStep__stepDetail__pic{src: "#{step.image}"}
              %p.recipeStep__stepDetail__comment=step.content
    =render 'show_post'
    =render 'show_related_recipes'