config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  devise_for :users
  resources :users, only: :show
  resources :tags, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/messages', to: 'messages#reply'
  resources :recipes do
    resources :favorites, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
  belongs_to :large_category
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/large_category.rb
class LargeCategory < ApplicationRecord
  has_many :categories
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :context, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :recipe
  has_many :messages, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user
  has_many :steps
  has_many :materials
  has_many :favorites,dependent: :destroy
  has_many :users, through: :favorites
  has_many :likes,dependent: :destroy
  has_many :users, through: :likes
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :questions, dependent: :destroy
  validates :name, :image, :comment, :category, presence: true
  accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :reject_steps
  # proc { |attributes| attributes['content'].blank? }
  accepts_nested_attributes_for :materials, allow_destroy: true, reject_if: :reject_materials
  # proc { |attributes| attributes['name'].blank? }
  
  mount_uploader :image, ImageUploader

  def reject_steps(attributes)
    exists = attributes[:id].present?
    empty = attributes[:content].blank?
    attributes.merge!(_destroy: 1) if exists && empty
    !exists && empty
  end

  def reject_materials(attributes)
    exists = attributes[:id].present?
    empty = attributes[:name].blank?
    attributes.merge!(_destroy: 1) if exists && empty
    !exists && empty
  end

  # タグ一覧の配列をeachで回し、それぞれのタグとrecipeのidをTag_mapに登録する
  def register_tags(tag_list)
    tag_list.each do |tag|
      TagMap.create(recipe_id: self.id, tag_id: tag.id)
    end
  end


  def update_tags(tag_list)
    delete_tags = self.tags - tag_list
    new_tags = tag_list - self.tags
    delete_tags.each{|tag| TagMap.find_by(recipe_id: self.id, tag_id: tag.id).delete}
    new_tags.each{|tag| TagMap.create(recipe_id: self.id, tag_id: tag.id)}
  end

end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
  mount_uploader :image, ImageUploader
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy
  has_many :recipes, through: :tag_maps
  validates :name, presence: true

  def self.set_tags(params)
    tag_lists = []
    params.each do |tag_array|
      # tag_arrayは[ 0, "タグの名前" ]が入っている
      tag_name = tag_array[1]
      unless tag_name == nil
        tag = Tag.where(name: tag_name).first_or_initialize
        tag.save
        tag_lists << tag
      end
    end
    return tag_lists
  end
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :recipes, through: :favorites
  has_many :recipes, through: :likes

  has_attached_file :avatar, styles: {medium: "300x300#", humb: "100x100#"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg", "image/jpeg", "image/png"]
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(recipe_id: params[:recipe_id], user_id: current_user.id)
    @recipe = Recipe.find(params[:recipe_id])
  end

  def destroy
    @like = Like.find(params[:id])
    @like.delete
    @like = nil
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipes, only: [:show, :edit]
  before_action :set_materials_and_steps, only: [:show, :edit]
  def index
    # ランキング機能はまだなので、仮に数字を入れる
    @rankings = Recipe.includes(:user).order('updated_at DESC').limit(10)
    @new_pickup = Recipe.last
    @new_rankings = Recipe.includes(:user).order('updated_at DESC').limit(6)
    @recipes = Recipe.includes(:user).page(params[:page]).per(12)
  end

  def show
    @recipe  = Recipe.find(params[:id])
    @favorite = Favorite.find_by(user_id: current_user.id, recipe_id: params[:id]) if signed_in?
    @like = Like.find_by(user_id: current_user.id, recipe_id: params[:id]) if signed_in?
    @message = Message.new

  end

  def new
    @recipe = Recipe.new
    6.times {
      @recipe.steps.build}
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      # タグの一覧を取得し、新しいタグは新規で登録
      tag_list = Tag.set_tags(params[:tag])
      # 取得したタグ一覧をTag_mapテーブルに保存
      @recipe.register_tags(tag_list)
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      tag_list = Tag.set_tags(params[:tag])
      @recipe.update_tags(tag_list)
      redirect_to @recipe
    else
      render :edit
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :comment, :build_time, :cost, :size, :point, :image, :category_id, steps_attributes: [:content, :image, :id], materials_attributes: [:name, :category, :id]).merge(user_id: current_user.id)
  end

  def set_recipes
    @recipe = Recipe.find(params[:id])
  end

  def set_materials_and_steps
    # レシピに紐づいているmaterialsのうち、categoryが0と1で分類し、それぞれを配列で保存。
    @materials_mate = @recipe.materials.select {|mate| mate.category == 0}
    @materials_tool = @recipe.materials.select { |mate| mate.category == 1}
    # こちらもコントローラで定義しておく。
    @steps = @recipe.steps
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @recipes = @tag.recipes.includes(:user).page(params[:page]).per(12)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @favo_recipes = Recipe.joins(:favorites).where("favorites.user_id = ?", current_user.id)
    @post_recipes = Recipe.joins(:user).where("users.id = ?", current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breadcrumbs_helper.rb
module BreadcrumbsHelper
  def add_breadcrumb(name, path)
    unless @_breadcrumbs
      @_breadcrumbs = [OpenStruct.new(name: "HOME", path: root_path)]
    end

    if @_breadcrumbs
      @_breadcrumbs << OpenStruct.new(name: name, path: path)
    end
  end

  def breadcrumbs
    @_breadcrumbs
  end
end

app/helpers/like_helper.rb
module LikeHelper
  def like_count
    @recipe.likes.size
  end
end

app/views/layouts/_header.html.haml
%header
  =link_to root_path do
    %h1.siteTitle DIYID
    %h2.siteTitle2.siteTitle__sub IYID
    %h3.siteTitle3.siteTitle__sub IYID
    %h4.siteTitle4.siteTitle__sub IYI
    %h3.siteTitle3.siteTitle__sub DIYI
    %h2.siteTitle2.siteTitle__sub DIYI
    %h1.siteTitle DIYID
  .rightContents
    %ul
      -if signed_in?
        %li.flame.flameRed.borderRight
          = link_to "ログアウト", destroy_user_session_path, method: :delete
        %li.flame.flameOrange
          = link_to "マイページ", user_path(current_user)
        %li.flame.flameBlue
          = link_to "レシピを投稿", new_recipe_path
      -else
        %li.flame.flameRed.borderRight
          = link_to "新規登録", new_user_registration_path
        %li.flame.flameBlue
          = link_to "ログイン", new_user_session_path
.globalNav
  %form.searchBox.clearfix
    %h4.searchBox__title
      =fa_icon 'search'
      ：キーワードで検索
    %input.searchBox__input{name: "search", type: "text", placeholder: "名前・材料で検索"}
    %button.searchBox__button{type: "submit"}
      = fa_icon 'search'
      検索
    .searchBox__recommendWord
      %h4 人気ワード：
      = link_to "ヒノキ", "#"
      = link_to "テーブル",'#'
      = link_to "トイレ周り", '#'

app/views/layouts/_side_bar.html.haml
.sideContent.searchAreaSide.clearfix
  %h2.sideContent__title.titleTop 
    =fa_icon 'search'
    キーワードで探す
  %form.searchBox
    %input.searchBox__input{name: "search", type: "text", placeholder: "名前・材料で検索"}
    %button.searchBox__button{type: "submit"}
      = fa_icon 'search'
      検索
    .searchBox__recommendWord
      %span 人気キーワード：
      = link_to "ヒノキ", "#"
      = link_to "テーブル",'#'
      = link_to "トイレ周り", '#'
.sideContent.searchGenres
  %h2.sideContent__title 
    =fa_icon 'indent'
    ジャンルで探す
  .genreWrapper
    .genre
      =fa_icon 'twitter 2x'
      %h4 ツイッタ
  .genreWrapper
    .genre
      =fa_icon 'twitter 2x'
      %h4 ツイッタ
  .genreWrapper
    .genre
      =fa_icon 'twitter 2x'
      %h4 ツイッタ
  .genreWrapper
    .genre
      =fa_icon 'twitter 2x'
      %h4 ツイッタ
  .genreWrapper
    .genre
      =fa_icon 'twitter 2x'
      %h4 ツイッタ
  .genreWrapper
    .genre
      =fa_icon 'twitter 2x'
      %h4 ツイッタ
.sideContent.searchCategories
  %h2.sideContent__title
    =fa_icon 'list'
    カテゴリで探す
    - LargeCategory.all.each do |large_cate|
      .categoryBlock
        .largeCategory.category
          = link_to '#' do
            .category__img
              = fa_icon 'bars 2x'
            .category__name
              %h4=large_cate.name
        -large_cate.categories.each do |cate|
          .smallCategory.category
            = link_to '#' do
              .category__img
                = fa_icon 'bars'
              .category__name
                %h4=cate.name

.sideContent.dailyRank.clearfix
  %h2.sideContent__title 
    = fa_icon 'anchor'
    ランキング
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu7.jpg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu2.jpg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu2.jpg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu3.jpeg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu4.jpeg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu5.jpg'}
      %p.subThumRecipe__title すげぇカツ丼

.sideContent.dailyRank.clearfix
  %h2.sideContent__title
    =fa_icon 'anchor'
    新着レシピ
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu7.jpg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu2.jpg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu2.jpg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu3.jpeg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu4.jpeg'}
      %p.subThumRecipe__title すげぇカツ丼
  .subThumRecipe
    = link_to '#' do
      %image.subThumRecipe__image{src: '/assets/katsu5.jpg'}
      %p.subThumRecipe__title すげぇカツ丼

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Diyid
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render '/layouts/header'
    .contentInner
      = yield :recipe_rank
      .mainContents
        - flash.each do |key, value|
          %div{class: "alert alert-#{key}"}
            = value
        = yield
      .sideContents
        = render '/layouts/side_bar'

app/views/shared/_breadcrumbs.html.haml
- if breadcrumbs.present?
  %ol.breadcrumbs
    - breadcrumbs.each do |breadcrumb|
      %li.breadcrumb
        - if breadcrumbs.last != breadcrumb
          = link_to breadcrumb.name, breadcrumb.path
        - else
          = breadcrumb.name

app/views/shared/_error_messages.html.haml
- if instance.errors.any?
  #error_explanation
    %ul
      - instance.errors.full_messages.each do |msg|
        %li= msg